# Site wide configuration

title: Sajidh Zahir
locale: en_US
description: /"Hello World/" Since 2012 😎.
logo: site-logo.jpg
search: true
url: https://sajidhz1.github.io/blog

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Sajidh Zahir
  avatar: bio-photo.jpg
  email: sajidhzazahir@gmail.com
  disqus-shortname: 
  twitter: sajidhz
  facebook: sajidh.zahir
  github: sajidhz1
  stackexchange: https://stackoverflow.com/users/1577428/sajidh-zahir
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
